---
identifier: "CVE-2018-1000808"
identifiers:
- "GMS-2018-277"
- "GHSA-2rcm-phc9-3945"
- "CVE-2018-1000808"
package_slug: "pypi/pyopenssl"
title: "Improper Resource Shutdown or Release"
description: "Python Cryptographic Authority pyopenssl contains a CWE - : Failure
  to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store
  that can result in Denial of service if memory runs low or is exhausted. This attack
  appear to be exploitable via Depends upon calling application, however it could
  be as simple as initiating a TLS connection. Anything that would cause the calling
  application to reload certificates from a PKCS #12 store.. This vulnerability appears
  to have been fixed "
date: "2021-08-31"
pubdate: "2018-10-10"
affected_range: "<17.5.0"
fixed_versions:
- "17.5.0"
affected_versions: "All versions before 17.5.0"
not_impacted: "All versions starting from 17.5.0"
solution: "Upgrade to version 17.5.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-1000808"
- "https://github.com/pyca/pyopenssl/pull/723"
- "https://access.redhat.com/errata/RHSA-2019:0085"
- "https://github.com/advisories/GHSA-2rcm-phc9-3945"
- "https://usn.ubuntu.com/3813-1/"
- "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html"
cvss_v2: "AV:N/AC:M/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
uuid: "dad8ca40-d564-4840-816d-3db0869be246"
cwe_ids:
- "CWE-1035"
- "CWE-404"
- "CWE-937"
