---
identifier: "CVE-2018-1000807"
identifiers:
- "GHSA-p28m-34f6-967q"
- "CVE-2018-1000807"
package_slug: "pypi/pyopenssl"
title: "Use After Free"
description: "Python Cryptographic Authority pyopenssl version contains a CWE-416:
  Use After Free vulnerability in X509 object handling that can result in Use after
  free can lead to possible denial of service or remote code execution.. This attack
  appear to be exploitable via Depends on the calling application and if it retains
  a reference to the memory.. This vulnerability appears to have been fixed "
date: "2021-08-31"
pubdate: "2018-10-10"
affected_range: "<17.5.0"
fixed_versions:
- "17.5.0"
affected_versions: "All versions before 17.5.0"
not_impacted: "All versions starting from 17.5.0"
solution: "Upgrade to version 17.5.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2018-1000807"
- "https://github.com/pyca/pyopenssl/pull/723"
- "https://access.redhat.com/errata/RHSA-2019:0085"
- "https://github.com/advisories/GHSA-p28m-34f6-967q"
- "https://usn.ubuntu.com/3813-1/"
- "http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00014.html"
cvss_v2: "AV:N/AC:M/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "197ab0c7-8d97-4ab3-a5e7-66149f00bd11"
cwe_ids:
- "CWE-1035"
- "CWE-416"
- "CWE-78"
- "CWE-937"
