---
identifier: "CVE-2014-8650"
identifiers:
- "GMS-2020-709"
- "GHSA-wh37-37xw-54hr"
- "CVE-2014-8650"
package_slug: "pypi/requests-kerberos"
title: "Improper Authentication"
description: "python-requests-Kerberos does not handle mutual authentication"
date: "2021-08-19"
pubdate: "2020-03-10"
affected_range: "<0.5"
fixed_versions:
- "0.6"
affected_versions: "All versions before 0.5"
not_impacted: "All versions starting from 0.5"
solution: "Upgrade to version 0.6 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2014-8650"
- "https://github.com/requests/requests-kerberos/issues/35"
- "https://github.com/requests/requests-kerberos/pull/36"
- "https://github.com/mkomitee/requests-kerberos/commit/9c1e08cc17bb6950455a85d33d391ecd2bce6eb6"
- "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2014-8650"
- "https://github.com/requests/requests-kerberos/blob/0.6/HISTORY.rst"
- "https://security-tracker.debian.org/tracker/CVE-2014-8650"
- "http://www.openwall.com/lists/oss-security/2014/11/07/1"
- "http://www.securityfocus.com/bid/70909"
- "https://github.com/advisories/GHSA-wh37-37xw-54hr"
cvss_v2: "AV:N/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
uuid: "ee131175-51d9-4069-b8ff-565f07a44cef"
cwe_ids:
- "CWE-1035"
- "CWE-287"
- "CWE-937"
