---
identifier: "CVE-2021-37654"
package_slug: "pypi/tensorflow"
title: "Out-of-bounds Read"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  The [implementation](https://github.com/tensorflow/tensorflow/blob/f24faa153ad31a4b51578f8181d3aaab77a1ddeb/tensorflow/core/kernels/resource_variable_ops.cc#L660-L668)
  does not check that the `batch_dims` value that the user supplies is less than the
  rank of the input tensor. Since the implementation uses several for loops over the
  dimensions of `tensor`, this results in reading data from outside the bounds of
  heap allocated buffer backing the tensor. We have patched the issue in GitHub commit
  bc9c546ce7015c57c2f15c168b3d9201de679a1d. The fix will be included in TensorFlow
  We will also cherrypick this commit on TensorFlow, TensorFlow, and TensorFlow, as
  these are also affected and still in supported range."
date: "2021-08-18"
pubdate: "2021-08-12"
affected_range: ">=2.3.0,<2.3.4||>=2.4.0,<2.4.3||>=2.5.0,<=2.6.0"
fixed_versions:
- "2.3.4"
- "2.4.3"
affected_versions: "All versions starting from 2.3.0 before 2.3.4, all versions starting
  from 2.4.0 before 2.4.3, all versions starting from 2.5.0 up to 2.6.0"
not_impacted: "All versions before 2.3.0, all versions starting from 2.3.4 before
  2.4.0, all versions starting from 2.4.3 before 2.5.0, all versions after 2.6.0"
solution: "Upgrade to versions 2.3.4, 2.4.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-37654"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H"
uuid: "c5ea84c5-2c3c-4cbf-9381-1affe31fdf25"
