---
identifier: "CVE-2021-29532"
package_slug: "maven/org.tensorflow/parentpom"
title: "Out-of-bounds Read"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  An attacker can force accesses outside the bounds of heap allocated arrays by passing
  in invalid tensor values to `tf.raw_ops.RaggedCross`. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/efea03b38fb8d3b81762237dc85e579cc5fc6e87/tensorflow/core/kernels/ragged_cross_op.cc#L456-L487)
  lacks validation for the user supplied arguments. Each of the above branches call
  a helper function after accessing array elements via a `*_list[next_*]` pattern,
  followed by incrementing the `next_*` index. However, as there is no validation
  that the `next_*` values are in the valid range for the corresponding `*_list` arrays,
  this results in heap OOB reads. The fix will be included in TensorFlow We will also
  cherrypick this commit on TensorFlow, TensorFlow, TensorFlow and TensorFlow, as
  these are also affected and still in supported range."
date: "2021-05-17"
pubdate: "2021-05-14"
affected_range: "(,2.1.4],[2.2.0,2.2.3],[2.3.0,2.3.3],[2.4.0,2.4.2]"
fixed_versions: []
affected_versions: "All versions up to 2.1.4, all versions starting from 2.2.0 up
  to 2.2.3, all versions starting from 2.3.0 up to 2.3.3, all versions starting from
  2.4.0 up to 2.4.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29532"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H"
uuid: "2efc71b5-e96c-459c-9083-eef7e641ee08"
