---
identifier: "CVE-2021-29617"
package_slug: "maven/org.tensorflow/parentpom"
title: "Improper Handling of Exceptional Conditions"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  An attacker can cause a denial of service via `CHECK`-fail in `tf.strings.substr`
  with invalid arguments. The fix will be included in TensorFlow We will also cherrypick
  this commit on TensorFlow, TensorFlow, TensorFlow and TensorFlow, as these are also
  affected and still in supported range."
date: "2021-05-17"
pubdate: "2021-05-14"
affected_range: "(,2.1.4],[2.2.0,2.2.3],[2.3.0,2.3.3],[2.4.0,2.4.2]"
fixed_versions: []
affected_versions: "All versions up to 2.1.4, all versions starting from 2.2.0 up
  to 2.2.3, all versions starting from 2.3.0 up to 2.3.3, all versions starting from
  2.4.0 up to 2.4.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29617"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "f79e1eb7-5bc7-4355-aaaa-3eaf1810bfcc"
