---
identifier: "CVE-2021-29567"
package_slug: "maven/org.tensorflow/parentpom"
title: "Reachable Assertion"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  Due to lack of validation in `tf.raw_ops.SparseDenseCwiseMul`, an attacker can trigger
  denial of service via `CHECK`-fails or accesses to outside the bounds of heap allocated
  data. Since the implementation(https://github.com/tensorflow/tensorflow/blob/38178a2f7a681a7835bb0912702a134bfe3b4d84/tensorflow/core/kernels/sparse_dense_binary_op_shared.cc#L68-L80)
  only validates the rank of the input arguments but no constraints between dimensions(https://www.tensorflow.org/api_docs/python/tf/raw_ops/SparseDenseCwiseMul),
  an attacker can abuse them to trigger internal `CHECK` assertions (and cause program
  termination, denial of service) or to write to memory outside of bounds of heap
  allocated tensor buffers. The fix will be included in TensorFlow We will also cherrypick
  this commit on TensorFlow, TensorFlow, TensorFlow and TensorFlow, as these are also
  affected and still in supported range."
date: "2021-05-19"
pubdate: "2021-05-14"
affected_range: "(,2.1.4),[2.2.0,2.2.3),[2.3.0,2.3.3),[2.4.0,2.4.2)"
fixed_versions: []
affected_versions: "All versions before 2.1.4, all versions starting from 2.2.0 before
  2.2.3, all versions starting from 2.3.0 before 2.3.3, all versions starting from
  2.4.0 before 2.4.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29567"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "d26ccdff-4a35-48d2-b22a-f039e72ec271"
