---
identifier: "CVE-2021-29582"
package_slug: "maven/org.tensorflow/parentpom"
title: "Out-of-bounds Read"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  Due to lack of validation in `tf.raw_ops.Dequantize`, an attacker can trigger a
  read from outside of bounds of heap allocated data. The implementation(https://github.com/tensorflow/tensorflow/blob/26003593aa94b1742f34dc22ce88a1e17776a67d/tensorflow/core/kernels/dequantize_op.cc#L106-L131)
  accesses the `min_range` and `max_range` tensors in parallel but fails to check
  that they have the same shape. The fix will be included in TensorFlow We will also
  cherrypick this commit on TensorFlow, TensorFlow, TensorFlow and TensorFlow, as
  these are also affected and still in supported range."
date: "2021-05-20"
pubdate: "2021-05-14"
affected_range: "(,2.1.4),[2.2.0,2.2.3),[2.3.0,2.3.3),[2.4.0,2.4.2)"
fixed_versions: []
affected_versions: "All versions before 2.1.4, all versions starting from 2.2.0 before
  2.2.3, all versions starting from 2.3.0 before 2.3.3, all versions starting from
  2.4.0 before 2.4.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29582"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H"
uuid: "6792d8d7-b745-4f2f-b553-2fe1fc5477bb"
