---
identifier: "CVE-2021-29619"
package_slug: "maven/org.tensorflow/parentpom"
title: "Improper Handling of Exceptional Conditions"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  Passing invalid arguments (e.g., discovered via fuzzing) to `tf.raw_ops.SparseCountSparseOutput`
  results in segfault. The fix will be included in TensorFlow We will also cherrypick
  this commit on TensorFlow, TensorFlow, TensorFlow and TensorFlow, as these are also
  affected and still in supported range."
date: "2021-05-18"
pubdate: "2021-05-14"
affected_range: "(,2.1.4),[2.2.0,2.2.3),[2.3.0,2.3.3),[2.4.0,2.4.2)"
fixed_versions: []
affected_versions: "All versions before 2.1.4, all versions starting from 2.2.0 before
  2.2.3, all versions starting from 2.3.0 before 2.3.3, all versions starting from
  2.4.0 before 2.4.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29619"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "530faffd-8e71-4c6c-a5d4-d2aae1896805"
